import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { describe, it } from "node:test";

function runScript(script, args = ["--stdout"]) {
  const result = spawnSync(process.execPath, [`scripts/${script}`, ...args], {
    cwd: new URL("..", import.meta.url),
    encoding: "utf8",
  });
  assert.equal(result.status, 0, `${script} failed\n${result.stdout}${result.stderr}`);
  return JSON.parse(result.stdout);
}

describe("admin scaffold safety plan", () => {
  it("keeps admin scaffold generation in dry-run mode behind generated-file boundaries", () => {
    const plan = runScript("generate-admin-scaffold-plan.mjs");

    assert.equal(plan.generatedBy, "scripts/generate-admin-scaffold-plan.mjs");
    assert.equal(plan.mode.dryRun, true);
    assert.equal(plan.mode.sourceWriting, "disabled");
    assert.equal(plan.mode.conflictDetection, "enabled");
    assert.deepEqual(plan.mode.allowedWriteRoots, ["resources/generated/scaffold/"]);
    assert.equal(plan.summary.conflictCount, 0);
    assert.equal(plan.summary.unsafePathCount, 0);
    assert.ok(plan.summary.candidateFileCount > 0, "expected template candidates to produce dry-run files");

    const candidates = plan.resources.flatMap((resource) => resource.candidateFiles);
    assert.ok(candidates.length > 0, "expected candidate files");
    for (const file of candidates) {
      assert.match(file.path, /^resources\/generated\/scaffold\//);
      assert.equal(file.conflict, false, file.path);
      assert.ok(file.eventualRuntimeTarget, `missing eventual target for ${file.path}`);
    }

    const manualReview = plan.resources.filter((resource) => resource.generationLevel === "manualReview");
    assert.ok(manualReview.length > 0, "expected custom resources to stay manual");
    assert.ok(manualReview.every((resource) => resource.candidateFiles.length === 0));
  });

  it("renders dry-run scaffold files only inside the generated scaffold root", () => {
    const manifest = runScript("generate-admin-scaffold-files.mjs");

    assert.equal(manifest.generatedBy, "scripts/generate-admin-scaffold-files.mjs");
    assert.equal(manifest.source, "resources/generated/admin-scaffold-plan.json");
    assert.equal(manifest.mode.sourceWriting, "disabled");
    assert.deepEqual(manifest.mode.allowedWriteRoots, ["resources/generated/scaffold/"]);
    assert.equal(manifest.summary.fileCount, manifest.files.length);
    assert.ok(manifest.summary.fileCount > 0, "expected scaffold files");

    const roles = new Set(manifest.files.map((file) => file.role));
    assert.ok(roles.has("repositoryDraft"));
    assert.ok(roles.has("routeDraft"));
    assert.ok(roles.has("refinePageDraft"));
    assert.ok(roles.has("contractTestDraft"));

    for (const file of manifest.files) {
      assert.match(file.path, /^resources\/generated\/scaffold\//);
      assert.equal(file.sourceWriting, "disabled");
      assert.equal(file.markerPresent, true, file.path);
      assert.match(file.contentSha256, /^[a-f0-9]{64}$/);
      assert.ok(file.preview.includes("Code generated by platform-go admin scaffold plan. DO NOT EDIT."), file.path);
      assert.ok(file.preview.includes("eventual runtime target:"), file.path);
    }
  });

  it("generates a non-mutating promotion review packet for target-family review", () => {
    const review = runScript("generate-admin-scaffold-promotion-review.mjs");

    assert.equal(review.generatedBy, "scripts/generate-admin-scaffold-promotion-review.mjs");
    assert.equal(review.mode.dryRun, true);
    assert.equal(review.mode.sourceWriting, "disabled");
    assert.equal(review.mode.runtimeMutation, "disabled");
    assert.equal(review.mode.promotion, "manual-review-required");
    assert.equal(review.manualReview.required, true);
    assert.equal(review.manualReview.decision, "not-approved");
    assert.equal(review.summary.conflictCount, 0);
    assert.equal(review.summary.unsafePathCount, 0);
    assert.ok(review.summary.targetFamilyCount >= 5, "expected target-family mappings");
    assert.ok(review.summary.generatedFileCount > 0, "expected generated scaffold artifacts");

    const families = new Map(review.targetFamilies.map((family) => [family.id, family]));
    for (const familyID of ["backend-models", "repositories", "api-routes", "admin-resource-pages", "contract-tests"]) {
      const family = families.get(familyID);
      assert.ok(family, `missing ${familyID} review family`);
      assert.ok(family.reviewItems.length > 0, `expected review items for ${familyID}`);
      assert.ok(family.testCommands.every((command) => command.startsWith("rtk ")), `expected rtk commands for ${familyID}`);
    }

    for (const item of review.targetFamilies.flatMap((family) => family.reviewItems)) {
      assert.match(item.scaffoldPath, /^resources\/generated\/scaffold\//);
      assert.equal(item.conflict, false, item.scaffoldPath);
      assert.equal(item.generatedArtifact, true, item.scaffoldPath);
      assert.match(item.contentSha256, /^[a-f0-9]{64}$/);
      assert.equal(item.reviewRequired, true);
    }
  });
});
